java_library(
    name = "core",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//application:__pkg__"],
    runtime_deps = [
        "@maven//:org_javamoney_moneta",
    ],
    deps = [
        "@maven//:javax_money_money_api",
    ],
)
