name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
      - run: bazel test //...
      - name: Save error logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: error-logs
          path: ~/.cache/bazel/**/*.log
